feat: replace @napi-rs/pinyin by pinyin-pro
lovell/limax pull request #48
Opened 2023-05-24 08:03 UTC by starcsb

2023-05-24 08:03 UTC, starcsb commented
close #47

2023-05-24 08:08 UTC, Brooooooklyn commented
This pr will decrease the performance while slugging Chinese input, ref: https://github.com/zh-lx/pinyin-pro/issues/99

2023-05-24 08:39 UTC, starcsb commented
> This pr will decrease the performance while slugging Chinese input, ref: [zh-lx/pinyin-pro#99](https://github.com/zh-lx/pinyin-pro/issues/99)
> 
> And I think the accurate issue is really easy to solve; the https://github.com/mozillazg/pinyin-data hasn't been updated for a long time.

I don't think it will decrease the performance. By my testing, only when the length of the text exceeds about `300k` can `@napi-rs/pinyin` perform better than `pinyin-pro`, and the performance difference does not exceed twice. But for most users, their input text will not too long. When the text length is within 100, the translation time for `pinyin-pro` is only 1ms, while the translation time for `@napi-rs/pinyin` is 150 milliseconds. Therefore, in the vast majority of cases, the performance of `pinyin-pro` is much higher than that of `@napi-rs/pinyin`.

2023-05-24 08:47 UTC, Brooooooklyn commented
As my description in https://github.com/zh-lx/pinyin-pro/issues/99, you are comparing `pinyin-pro` with the `segment` option enabled with `@napi-rs/pinyin`, which is unfair; because 1. `pinyin-pro` doesn't support `segment` feature 2. `limax` project doesn't use `segment` feature. From my benchmark, for the **100 words input**, the benchmark result shows:

```
❯ node speed.js  
pinyin-pro 转换 100 字数时间: 0.582ms
pinyin 转换 100 字数时间: 0.292ms
@napi-rs/pinyin 转换 100 字数时间: 0.041ms
```

Which is significantly different

2023-05-24 08:52 UTC, starcsb commented
> As my description in [zh-lx/pinyin-pro#99](https://github.com/zh-lx/pinyin-pro/issues/99), you are comparing `pinyin-pro` with the `segment` option enabled with `@napi-rs/pinyin`, which is unfair; because 1. `pinyin-pro` doesn't support `segment` feature 2. `limax` project doesn't use `segment` feature. From my benchmark, for the **100 words input**, the benchmark result shows:
> 
> ```
> ❯ node speed.js  
> pinyin-pro 转换 100 字数时间: 0.582ms
> pinyin 转换 100 字数时间: 0.292ms
> @napi-rs/pinyin 转换 100 字数时间: 0.041ms
> ```
> 
> Which is significantly different

As the author's reply, pinyin-pro defaults to having segment enabled in all cases(otherwise it wouldn't have such high accuracy), this option doesn't need to be opened by the user manually. So the performance should by compared with `segment` enabled.

2023-05-24 08:59 UTC, Brooooooklyn commented
> So the performance should by compared with segment enabled

Okay, sure, but the `limax` doesn't need the `segment` option, the `@napi-rs/pinyin` is still ***14x faster*** in this case.

2023-05-24 09:07 UTC, starcsb commented
> > So the performance should by compared with segment enabled
> 
> Okay, sure, but the `limax` doesn't need the `segment` option, the `@napi-rs/pinyin` is still _**14x faster**_ in this case.

But if don't open `segment`, how to ensure the accuracy? I think `segment` is the key of improving accuracy.

2023-05-24 09:09 UTC, starcsb commented
The core purpose of this PR is to improve accuracy rather than performance. The upgrade of [mozillazg/pinyin-data](https://github.com/mozillazg/pinyin-data) does not significantly improve accuracy

2023-05-24 09:39 UTC, Brooooooklyn commented
@starcsb you are right, after checking the source code from `pinyin-pro`, I realized that combing segment and phrase is a better way to improve both performance and accuracy. Thanks for the discussion, I'll post these back to the `rust-pinyin`.

2023-05-25 09:35 UTC, lovell commented on package.json
> +    "pinyin-pro": "^3.14.0"
Given `pinyin-pro` is not a native module, we could promote it to standard `dependencies` and remove the try/catch block around its `require` statement.

2023-05-25 09:36 UTC, lovell commented on test/unit.js
> +  t.true(
Thanks for adding tests. These will also require the following change:
```diff
- t.plan(3);
+ t.plan(5);
```

2023-05-26 02:36 UTC, starcsb commented
> Thank you for the PR, I've left a couple of comments inline.

Thanks for your comments, I have modified these.

2023-05-26 08:24 UTC, starcsb commented
> Thank you for the PR, I've left a couple of comments inline.

Thanks for your comments, I have modified them.

2023-05-26 10:48 UTC, lovell requested changes

2023-05-26 10:48 UTC, lovell commented on lib/limax.js
>  let pinyin, PINYIN_STYLE;
Line 6 can be removed.

2023-05-26 12:58 UTC, starcsb commented
<img width="559" alt="图片" src="https://github.com/lovell/limax/assets/121841159/ed4ceb0a-6db4-4dc5-98a8-1473b804679e">

@lovell I corrected a [original test case](https://github.com/lovell/limax/pull/48/files#diff-6c4ac77163e8ec13146b6400fa4efab193dab7668284713a1165867c62fcbbbbL14-R14). In chinese, the pinyin of `弄堂` should be `long4 tang2` rather than `nong4 tang2`. It still relies on `pinyin-pro` to discover this problem.

See more detail: [弄堂](https://baike.baidu.com/link?url=yL3DKJp2jVUoR0BC3iJds9gfDlJsSnqq4Lpr8y5JiauNO6mZ_3PL03JipDGjaGhh8GTKOpVoTAmD6uQCTEPF5S-ht3TfyeRi0MzO7hvtuNW)

<img width="840" alt="图片" src="https://github.com/lovell/limax/assets/121841159/69462935-4447-4934-ba73-236813a82f41">

2023-05-30 11:20 UTC, lovell approved these changes

2023-05-30 11:31 UTC, merged

2023-05-30 12:44 UTC, lovell commented
v4.1.0 now available, thank you.